feat(model): allow asynchronous on multi-instance characteristics
camunda/camunda-bpmn-model pull request #25
Opened 2019-11-29 13:37 UTC by tiesebarrell

This feature allows to configure the asynchronous behaviour of element activities of a multi-instance activity from the fluent builder API, in addition to the existing feature to set the asynchronous behaviour for the whole multi-instance body.

2019-12-05 10:41 UTC, mboskamp commented
Hi @tiesebarrell,

thank you for your contribution. I opened CAM-11160 to track the PR in our issue tracker.
Somebody of the development team will have a look into your changes and will come back to you.

Best,
Miklas

2019-12-10 16:27 UTC, ThorbenLindhauer requested changes
Hi Tiese,

Thanks for the contribution, the code looks fine. Could you please add a test case to `ProcessBuilderTest` though? E.g. by extending this test case: https://github.com/camunda/camunda-bpmn-model/blob/7.12.0/src/test/java/org/camunda/bpm/model/bpmn/builder/ProcessBuilderTest.java#L2051-L2079

Cheers,
Thorben

2019-12-12 12:51 UTC, tiesebarrell commented
> Could you please add a test case to `ProcessBuilderTest` though? E.g. by extending this test case: https://github.com/camunda/camunda-bpmn-model/blob/7.12.0/src/test/java/org/camunda/bpm/model/bpmn/builder/ProcessBuilderTest.java#L2051-L2079

- Added two test cases.

2019-12-12 14:05 UTC, ThorbenLindhauer approved these changes

2019-12-12 14:06 UTC, ThorbenLindhauer commented
Thanks for providing the test. In the last days we have merged the model API repositories into camunda-bpm-platform, so I have applied your contribution there: https://github.com/camunda/camunda-bpm-platform/commit/7fb67f34086cb2d24b8d56da6a6a18860a6d717c

2019-12-12 14:06 UTC, closed without merging